# Generated by Django 4.2.1 on 2023-05-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_shipment_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='receiver_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
